Login:
      login_with_sso_btn: "//*[contains(text(), 'Login with SSO')]"
      login_username: "#gigya-loginID-77152811960799260"
      username: "udaykumar.reddy@yokogawa.com"
      password: "uday@10051808"
      signin_1: "//*[@id='gigya-login-form']/div[2]/div[3]/div[5]/input"
      login_password: "#gigya-password-116353530441464400"
      otp: ".cb-section_column input[class*='code-textbox']"
      submit: "#container_showTfaUI_1_wrapper > div.gig-tfa-button-container > div"
UserManagement:
      userManagement_btn : "//*[contains(text(), 'User Management')]"
      createnew: "div.col-sm-7 > div > a"
      emailaddress: "div:nth-child(4) > input"
      username: "div:nth-child(5) > input"
      pwd: "div:nth-child(6) > div:nth-child(1) > input"
      confirm_pwd: "div:nth-child(6) > div:nth-child(2) > input"
      firstname: "div:nth-child(7) > div:nth-child(1) > input"
      lastname: "div:nth-child(7) > div:nth-child(2) > input"
      phonenumber: "div:nth-child(8) > input"
      address: "div:nth-child(9) > input"
      city: "div:nth-child(10) > input"
      state: "div:nth-child(11) > input"
      country: "div:nth-child(12) > div:nth-child(1) > select"
      postalcode: "div:nth-child(12) > div:nth-child(2) > input"
      superadmin: "input[name='is_superadmin']"
      login_as_engineer: "div:nth-child(12) > div:nth-child(4) > div > label"
      login_as_customer: "div:nth-child(12) > div:nth-child(5) > div > label"
      role: ".card-body .form-control .filter-option"
      tenant_admin: ".inner.show#bs-select-4 li:nth-of-type(2)"
      customer_admin: ".inner.show#bs-select-4 li:nth-of-type(3)"
      customer: ".inner.show#bs-select-4 li:nth-of-type(4)"
      application: "div:nth-child(3) > div > div > button > div"
      bi_dashboard: ".inner.show#bs-select-5 li:nth-of-type(1)"
      housekeeper_dashboard: ".inner.show#bs-select-5 li:nth-of-type(2)"
      engineering_console: ".inner.show#bs-select-5 li:nth-of-type(3)"
      bi_reports: ".inner.show#bs-select-5 li:nth-of-type(4)"
      save: "nav > div > div > button"
      creation_status: ".container-fluid .content-header + div"
UserManagement_InputData:
      emailaddress: "udayreddy08042022+2@gmail.com"
      username: "udayreddy2"
      pwd: "QAtest123"
      confirm_pwd: "QAtest123"
      firstname: "Uday"
      lastname: "Reddy"
      phonenumber: "8121315997"
      address: "Bangalore"
      city: "Bangalore"
      state: "Karnataka"
      country: "India"
      postalcode: "560103"
UserManagement_Updateuser_Selectors:
      userManagement_btn : "//*[contains(text(), 'User Management')]"
      createnew: "div.col-sm-7 > div > a"
      emailaddress: "div:nth-child(4) > input"
      username: "div:nth-child(5) > input"
      firstname: "div:nth-child(6) > div:nth-child(1) > input"
      lastname: "div:nth-child(6) > div:nth-child(2) > input"
      phonenumber: "div:nth-child(7) > input"
      address: "div:nth-child(8) > input"
      city: "div:nth-child(9) > input"
      state: "div:nth-child(10) > input"
      country: "div:nth-child(11) > div:nth-child(1) > select"
      postalcode: "div:nth-child(11) > div:nth-child(2) > input"
      superadmin: "input[name='is_superadmin']"
      login_as_engineer: "input[name='login_as_engineer']"
      login_as_customer: "div:nth-child(12) > div:nth-child(5) > div > label"
      role: ".card-body .form-control .filter-option"
      tenant_admin: ".inner.show#bs-select-4 li:nth-of-type(2)"
      customer_admin: ".inner.show#bs-select-4 li:nth-of-type(3)"
      customer: ".inner.show#bs-select-4 li:nth-of-type(4)"
      application: "div:nth-child(3) > div > div > button > div"
      bi_dashboard: ".inner.show#bs-select-5 li:nth-of-type(1)"
      housekeeper_dashboard: ".inner.show#bs-select-5 li:nth-of-type(2)"
      engineering_console: ".inner.show#bs-select-5 li:nth-of-type(3)"
      bi_reports: ".inner.show#bs-select-5 li:nth-of-type(4)"
      save: ".fixed-bottom button[type='submit']"
      creation_status: ".container-fluid .content-header + div"

UserManagement_UpdateData:
      emailaddress: "udayreddy08042022+2@gmail.com"
      username: "udayreddy2"
      firstname: "Uday Kumar"
      lastname: "Reddy"
      phonenumber: "8121315997"
      address: "Hyderabad"
      city: "Bangalore"
      state: "Karnataka"
      country: "India"
      postalcode: "560103"

UserManagement_Actions:
      search_bar: "input[type='search']"
      search_table: "tr[data-index='0'] .editrow"
      user_settings: "tr[data-index='0'] .userActionBtn"
      extract_email: "tr[data-index='0'] td:nth-of-type(2)"
      tab_header: ".modal-header"
      deactivate_user: "//*[contains(text(), 'Deactivate')]"
      activate_user: "//*[contains(text(), 'Activate')]"
      disabled_status: "//*[contains(text(), 'Disabled')]"
      enabled_status: "//*[contains(text(), 'Active')]"
      enable_tfa: "//*[contains(text(), 'Enable TFA')]"
      reset_tfa: "//*[contains(text(), 'Reset TFA')]"
      reset_pwd: "//*[contains(text(), 'Reset Password')]"
      delete_user: "//*[contains(text(), 'Delete Permanently')]"
      modal_close_btn: "#userActionModal .close"
      error_page: ".flex-center .message"
      delete_msg: ".content-header + .alert"
      no_records_msg: "#user_table tbody .no-records-found"

UM_Refresh_Option:
      refresh_btn: "div.columns.columns-right.btn-group.float-right > button > i"
      number_of_records: ".pagination-info"

UM_Toggle_Option:
      toggle_btn: "div.columns.columns-right.btn-group.float-right > div > button"
      toggle_check_btn: ".dropdown-menu.dropdown-menu-right.show > label:nth-child(1) > input"

UM_Sorting_Fields:
      sort_email_address: "//div[contains(text(), 'E-mail Address')]"
      sort_first_name: "//div[contains(text(), 'First Name')]"
      sort_last_name: "//div[contains(text(), 'Last Name')]"
      sort_status: "//*/th[5]/div[1]"
      sort_verified_status: "//div[contains(text(), 'Verified Status')]"

UM_Plus_Option:
      plus_option_btn: "tr:nth-child(1) > td:nth-child(1) > a > i"
      tenant_data: "//*[@id='user_table']/tbody/tr[2]/td/table/tbody/tr/td[1]"
      role_data: "//*[@id='user_table']/tbody/tr[2]/td/table/tbody/tr/td[2]"
      application_data: "//*[@id='user_table']/tbody/tr[2]/td/table/tbody/tr/td[3]"

InvitationManagement:
      InvitationManagement_btn: "//div[@class='sidebar'] //*[contains(text(), 'Invitation Management')]"
      createnew: "div.col-sm-7 > div > a:nth-child(1)"
      download_template: "div.col-sm-7 > div > a:nth-child(2)"
      download_filepath: "Downloads"
      download_template_filename: "Invitation Template.xlsx"
      upload_template: "div.col-sm-7 > div > button"
      choose_file: "div.modal-body > div > input"
      upload_file_submit: "button.btn.btn-primary"
      upload_file_status: "div.alert.alert-success"
      upload_file_error_status: "div.alert.alert-danger"
      upload_file: "Upload Template.xlsx"
      delete_btn: ".bs-bars #remove_btn"
      search_bar: "input[type='search']"
      search_table: "tr[data-index='0'] .bs-checkbox"
      emailaddress: "input[name='email[0]']"
      firstname: "input[name='first_name[0]']"
      lastname: "input[name='last_name[0]']"
      addtenant: "button[data-target='#addTenantModal']"
      select_tenant: "button[data-id='tenant_list']"
      select_tenant_name: "#bs-select-1 li:nth-of-type(3)"
      select_role: "button[data-id='role_list']"
      select_rolename: "#bs-select-2 li:nth-of-type(2)"
      select_application: "#app_list_formgrp"
      select_applicationname: "#bs-select-3 li:nth-of-type(1)"
      add_tenant_btn: "#add_tenant_submit"
      save: ".card-footer button[type='submit']"
      card_title: "#tenant_assignment_div_0 .card-title"
      role_selected: "button[data-id='role_assigned0_1']"
      application_selected: "button[data-id='app_assigned0_1']"
      inviteuserstatus: ".container-fluid .content-header + div"

InvitationManagement_InputData:
      emailaddress: "udayreddy08042022+3@gmail.com"
      firstname: "uday"
      lastname: "reddy3"
      delete_mail_id: "example@example.com"

IM_Refresh_Option:
      refresh_btn: "div.columns.columns-right.btn-group.float-right > button"
      number_of_records: "div.float-left.pagination-detail > span"

IM_Toggle_Option:
      toggle_btn: "div.columns.columns-right.btn-group.float-right > div > button"
      toggle_check_btn: ".dropdown-menu.dropdown-menu-right.show > label:nth-child(1) > input"

IM_Sorting_Fields:
      sort_email_address: "//div[contains(text(), 'E-mail Address')]"
      sort_tenants: "//div[contains(text(), 'Tenants')]"
      sort_invited_date: "//div[contains(text(), 'Invited Date')]"
      sort_invitation_expiry: "//div[contains(text(), 'Invitation Expiry')]"
      sort_invitation_status: "//div[contains(text(), 'Invitation Status')]"

IM_Plus_Option:
      plus_option_btn: "tr:nth-child(1) > td:nth-child(1) > a > i"
      tenant_data: "//*[@id='invitation_table']/tbody/tr[2]/td/table/tbody/tr/td[1]"
      role_data: "//*[@id='invitation_table']/tbody/tr[2]/td/table/tbody/tr/td[2]"
      application_data: "//*[@id='invitation_table']/tbody/tr[2]/td/table/tbody/tr/td[3]"

Log_viewer:
      log_viewer_btn: "li:nth-child(4) > a"
      log_btn: "li:nth-child(4) > ul > li > a"
      download_log: "tr:nth-child(1) > td.text-right > div > a.btn.btn-sm.btn-success > i"
      download_filepath: "Downloads"
      log_filename: "laravel-"





